# Generated by Django 4.1.7 on 2023-04-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20230403_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
